create database DB_LOCADORA;
use DB_LOCADORA;

create table TB_CLIENTE
(
CD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NM_CLIENTE VARCHAR (50),
NM_ENDERECO VARCHAR (50),
NU_ENDERECO INT
);

create table TB_COR
(
CD_COR INT PRIMARY KEY AUTO_INCREMENT,
NM_COR VARCHAR (50)
);

create table TB_FORNECEDOR
(
CD_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
NM_FORNECEDOR VARCHAR(50),
NM_ENDERECO VARCHAR(50), 
NU_ENDERECO INT,
NU_CNPJ INT,
NU_TELEFONE INT
);

create table TB_MARCA
(
CD_MARCA int primary key auto_increment,
NM_MARCA VARCHAR (50),
ID_FORNECEDOR INT,
constraint FK_TB_MARCAS_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) references TB_FORNECEDOR(CD_FORNECEDOR)
);

create table TB_MODELO
(
CD_MODELO INT primary key auto_increment,
NM_MODELO VARCHAR (50),
ID_MARCA INT,
constraint FK_TB_MODELO_MARCA FOREIGN KEY (ID_MARCA) references TB_MARCA(CD_MARCA)
);

create table TB_VEICULO
(
CD_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
NM_MODELO  VARCHAR (50),
NU_PLACA INT,
VL_VEICULO DECIMAL(9,2),
ID_MODELO INT,
ID_COR INT,
constraint FK_TB_VEICULO_MODELO FOREIGN KEY (ID_MODELO) references TB_MODELO(CD_MODELO),
constraint FK_TB_VEICULO_COR FOREIGN KEY (ID_COR) references TB_COR(CD_COR)
);

create table TB_MANUTENCAO
(
CD_MANUTENCAO INT PRIMARY KEY AUTO_INCREMENT,
VL_MANUTENCAO DECIMAL (9,2),
DT_MANUTENCAO DATE, 
ID_MODELO INT,
constraint FK_TB_MANUTENCAO_MODELO foreign key (ID_MODELO) references TB_MODELO(CD_MODELO)
);

create table TB_CONTRATO
(
CD_CONTRATOS INT PRIMARY KEY AUTO_INCREMENT,
DT_EMISSAO DATE,
DT_VENCIMENTO DATE,
VL_SEGURO DECIMAL(9,2),
VL_DIARIA DECIMAL (9,2),
NM_PLACA VARCHAR (7),
ID_CLIENTE INT,
ID_VEICULO INT,
constraint 	FK_TB_CONTRATO_VEICULO FOREIGN KEY (ID_VEICULO) references TB_VEICULO(CD_VEICULO),
constraint FK_TB_CONTRATO_CLIENTE FOREIGN KEY (ID_CLIENTE) references TB_CLIENTE(CD_CLIENTE)
);
