/*Alunos: Vitória e Matheus Vedovelli */

create database DB_PRODUTO;
use DB_PRODUTO;

create table TB_CATEGORIA
(
CD_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NM_CATEGORIA VARCHAR(50)
);

create table TB_CLIENTE
(
CD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NM_CLIENTE VARCHAR (65),
NU_CPF CHAR (11)
);

create table TB_PRODUTO
(
CD_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NM_PRODUTO VARCHAR (65),
DS_PRODUTO  VARCHAR (65),
VL_PRODUTO DECIMAL (9,2),
QT_PRODUTO INT,
ID_CATEGORIA INT,
constraint FK_CATEGORIA_PROD FOREIGN KEY (ID_CATEGORIA) references TB_CATEGORIA(CD_CATEGORIA) 
);

create table TB_VENDA
(
CD_VENDA INT PRIMARY KEY AUTO_INCREMENT,
NM_VENDEDOR VARCHAR (65),
DT_VENDA DATE,
VL_TOTAL decimal (9,2),
ID_CLIENTE int,
constraint FK_CLIENTE_VENDA FOREIGN KEY (ID_CLIENTE) references TB_CLIENTE(CD_CLIENTE)
);

create table TB_ITEM_VENDA
(
ID_PRODUTO INT,
ID_VENDA INT,
VL_UNITARIO DECIMAL (9,2),
constraint PK_PRODUTO_VENDA PRIMARY KEY (ID_PRODUTO, ID_VENDA),
constraint FK_PRODUTO_ITEMVENDA FOREIGN KEY (ID_PRODUTO) references TB_PRODUTO(CD_PRODUTO),
constraint FK_VENDA FOREIGN KEY (ID_VENDA) references TB_VENDA(CD_VENDA)
);


